language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=android-29
    - ANDROID_BUILD_TOOL_VERSION=build-tools-28.0.3
    - ANDROID_EMULATOR_LEVEL=android-22
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools
    - $ANDROID_BUILD_TOOL_VERSION
    - $ANDROID_API_LEVEL
    - extra-android-m2repository
script:
  - ./gradlew build -x test
